import {
    AppWindow,
    BarChart3,
    Binary,
    Bot,
    Brain,
    Briefcase,
    Brush,
    Building2,
    Bug,
    Cloud,
    CloudCog,
    Code2,
    Container,
    Cpu,
    Database,
    FileCode2,
    Fingerprint,
    GitBranch,
    GitMerge,
    Globe,
    HardDrive,
    Laptop,
    LayoutTemplate,
    LineChart,
    Lock,
    MessageSquare,
    Monitor,
    MonitorSmartphone,
    Network,
    Palette,
    PanelsTopLeft,
    PenTool,
    PieChart,
    Server,
    Shield,
    ShieldCheck,
    Smartphone,
    Sparkles,
    Tablet,
    Terminal,
    Users,
    Workflow,
    Zap,
} from "lucide-react";

export const SERVICE_ICONS = {
    code: Code2,
    fileCode: FileCode2,
    binary: Binary,
    bug: Bug,

    terminal: Terminal,
    workflow: Workflow,

    globe: Globe,
    monitor: Monitor,
    monitorSmartphone: MonitorSmartphone,
    laptop: Laptop,

    layout: PanelsTopLeft,
    template: LayoutTemplate,

    server: Server,
    database: Database,
    hardDrive: HardDrive,
    network: Network,

    cloud: Cloud,
    cloudCog: CloudCog,

    palette: Palette,
    brush: Brush,
    penTool: PenTool,

    smartphone: Smartphone,
    tablet: Tablet,
    appWindow: AppWindow,

    gitBranch: GitBranch,
    gitMerge: GitMerge,
    container: Container,

    bot: Bot,
    brain: Brain,
    cpu: Cpu,
    sparkles: Sparkles,
    zap: Zap,

    chart: BarChart3,
    lineChart: LineChart,
    pieChart: PieChart,

    shield: Shield,
    shieldCheck: ShieldCheck,
    lock: Lock,
    fingerprint: Fingerprint,

    briefcase: Briefcase,
    building: Building2,
    users: Users,
    message: MessageSquare,
};